server {
    listen 80 default_server;
    server_name _;  # Принимаем все домены, можно указать конкретный домен
    
    client_max_body_size 20M;
    
    access_log /var/log/nginx/gross-community.access.log;
    error_log  /var/log/nginx/gross-community.error.log;

    # Проксируем все запросы на Docker Nginx (который работает на порту 8080)
    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_intercept_errors on;
        error_page 404 = @fallback;
    }

    # Fallback для ошибок
    location @fallback {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

