[program:laravel-queue-worker]
process_name=%(program_name)s_%(process_num)02d
command=docker exec php-fpm-gross php artisan queue:work rabbitmq --verbose --tries=3 --timeout=30
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/laravel-queue-worker.log
stopwaitsecs=3600
